name: Das deploy

on:
  pull_request:
    types: [closed]

jobs:
  Explore-GitHub-Actions:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install packages
        run: npm ci

      - name: Bundle
        run: npm run build
