name: Das deploy
on: [push]
jobs: 
  Explore-GitHub-Actions:
    runs-on: ububtu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Intall packages
        run: npm ci
      - name: Bundle
        run: npm run build
